name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build the project
        run: go build -v ./...

      - name: Print GitHub Ref
        run: echo $GITHUB_REF

      - name: Create a tag
        id: create_tag
        run: |
          # Set up Git credentials with GITHUB_TOKEN
          TAG_NAME="v1.1.0"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME
          echo "Created and pushed tag: $TAG_NAME"
      

      - name: List tags in the repository
        run: git tag
      

      - name: Upload new asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: example.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: refs/tags/v1.0.0
      
