name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Create output directory
        run: mkdir -p cmd/KV-Toolbox/output\
    
      - name: cd cmd
        run : ls

      - name: Build for macOS
        run: |
          cd cmd/KV-Toolbox
          fyne package -os darwin -icon icon.png -name ManageDB
          mv ManageDB.app output

      - name: List output directory
        run: ls cmd/KV-Toolbox/output

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-macos
          path: cmd/KV-Toolbox/output

  build-windows:
    needs: build-macos
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Create output directory
        run: mkdir cmd/KV-Toolbox/output

      - name: Build for Windows
        run: |
          cd cmd/KV-Toolbox
          fyne package -os windows -icon icon.png -name ManageDB
          mv ManageDB.exe output

      - name: List output directory
        run: dir cmd\KV-Toolbox\output

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-windows
          path: cmd/KV-Toolbox/output

  build-linux:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Create output directory
        run: mkdir -p cmd/KV-Toolbox/output

      - name: Build for Linux
        run: |
          cd cmd/KV-Toolbox
          fyne package -os linux -icon icon.png -name ManageDB
          mv ManageDB output/ManageDB-linux

      - name: List output directory
        run: ls cmd/KV-Toolbox/output

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-linux
          path: cmd/KV-Toolbox/output
