name: Update Release with example.txt

on:
  push:
    branches:
      - main  # این کار فقط زمانی اجرا می‌شود که به شاخه main پوش شود.

jobs:
  update-release:
    runs-on: ubuntu-latest  # اجرا روی سیستم Ubuntu

    steps:
      # 1. چک کردن کدهای پروژه
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. استفاده از اکشن برای ایجاد یا بروز رسانی ریلیز
      - name: Create or Update Release
        id: release
        run: |
          # استفاده از GitHub CLI برای دریافت یا ساخت ریلیز
          release=$(gh release list --repo $GITHUB_REPOSITORY | grep "v" | head -n 1)
          if [ -z "$release" ]; then
            # اگر ریلیزی وجود نداشته باشد، ریلیز جدید ایجاد می‌کنیم
            gh release create v1.0.0 example.txt --repo $GITHUB_REPOSITORY
          else
            # اگر ریلیز وجود داشته باشد، آن را بروز می‌کنیم
            gh release upload v1.0.0 example.txt --repo $GITHUB_REPOSITORY --clobber
          fi

      # 3. استفاده از اکشن برای آپلود فایل به ریلیز
      - name: Upload new asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: example.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
