name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Fyne CLI
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Create output directory
        run: mkdir -p cmd/KV-Toolbox/output

      - name: Build for each OS
        run: |
          cd cmd/KV-Toolbox
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            fyne package -os darwin -icon icon.png -name ManageDB
            mv ManageDB.app output
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            fyne package -os windows -icon icon.png -name ManageDB
            mv ManageDB.exe output
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            fyne package -os linux -icon icon.png -name ManageDB
            mv ManageDB output/ManageDB-linux
          fi
        shell: bash

      - name: List output directory
        run: ls cmd/KV-Toolbox/output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output-files-${{ matrix.os }}
          path: cmd/KV-Toolbox/output
