name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev


      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Create output directory
        run: mkdir -p output

      - name: Build for Linux
        run: |
          fyne package -os linux -icon icon.png -name ManageDB
          mv ManageDB output/ManageDB

      - name: List output directory
        run: ls output

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-linux
          path: output

  build-windows:
    needs: build-linux
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          echo "C:\Users\runneradmin\go\bin" >> $env:GITHUB_PATH
          fyne version

      - name: Create output directory
        run: mkdir output

      - name: Build for Windows
        run: |
          fyne package -os windows -icon icon.png -name ManageDB
          mv ManageDB.exe output

      - name: List output directory
        run: dir output

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-windows
          path: output

  build-macos:
    needs: build-windows
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Create output directory
        run: mkdir -p output

      - name: Build for macOS
        run: |
          fyne package -os darwin -icon icon.png -name ManageDB
          mv ManageDB.app output

      - name: List output directory
        run: ls output

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-macos
          path: output
